### PR TITLE
CSS visibility steps

### PR DESCRIPTION
**Pull request by day-me-an**

### CODE REVIEW

**Comment by ggozad** [comment]
Hi Damien,
I merged your other two PRs.
Concerning this one:
I would like to avoid deprecating steps. Perhaps a way to do that would be to keep ```When I see ...``` for existence and then add steps for visibility. These should be phrased as:

"Then the element with css ... should be visible"
"Then there should be X visible elements with ..."

Another way to support adding the "existance" keyword would be to simply add the step name. For example:

```
@step(u'the element with  id "{id}" should exist')
@step(u'I should see an element with id "{id}"')
@persona_vars
def should_see_element_with_id(context, id):
    assert context.browser.is_element_present_by_id(id), u'Element not found'
``` 


Let me know what you think.

**Comment by day-me-an** [comment]
Hi Yiorgis

I should get those changes done by the end of the week.

Thanks

**Comment by day-me-an** [comment]
Do you still want to keep the phrasing `the css selector "{css}"` ? This is used for all the existing steps that I've seen in behaving.

**Comment by ggozad** [comment]
Yes please. It's not great, but I want to avoid breaking everybody's tests :)

**Comment by day-me-an** [comment]
I mean for the new step names, so:

`Then the element with the css selector "{css}" should be visible`

instead of

`Then the element with css "{css}" should be visible`

**Comment by ggozad** [comment]
I think using "css selector" is correct.

**Comment by day-me-an** [comment]
Ok, done.

**Comment by ggozad** [comment]
Hey!
Sorry for being so difficult, but is it possible to again rename so that they make better sense in English?

For example:
"Then I should not see an element visible with the css selector "#slowly-visible-list" within 0 seconds"
should be:
"Then the element with the css selector "..." should be visible within 0 seconds"

Or:

I should see an element visible with the css selector "{css}"
should be
the element with css selector "{css}" should be visible

I am away for a week and very slow at this, but late next week will be able to merge and release if all ok.

**Comment by ggozad** [comment]
I've done the renaming and some minor fixes on the css_visibility branch. Could you please check it out and if happy I will merge.

**Comment by day-me-an** [comment]
Looks good to me

**Comment by ggozad** [comment]
Merged and released

**Pull request closed without merging**
