### PR TITLE
Parse context.text for persona vars.

### PR DESCRIPTION
**Pull request by MihaiBalint**
In addition to replacing persona variables in step parameters this change replaces persona variables in context.text if it is available. 

For testing purposes I also added a step to assign context.text to a persona variable.

### CODE REVIEW

**Comment by ggozad** [comment]
Excellent Mihai, I didn't know you could actually do that :)
Would you mind updating the README and CHANGELOG as well with your name? I am sick but will test and merge asap.

**Comment by MihaiBalint** [comment]
$ ./bin/test --tags personas --tags ~sms
===== snip =====  snip ===== snip =====
Feature: Use Personas # src/behaving/tests/features/personas.feature:1

  @personas
  Scenario: Get/Set variables          # src/behaving/tests/features/personas.feature:4
    Given "Foo" as the persona         # src/behaving/personas/steps.py:7 2.107s
    When I set "bar" to "Hello world"  # src/behaving/personas/persona.py:40 0.000s
    Then "bar" is set to "Hello world" # src/behaving/personas/persona.py:40 0.000s

  @personas
  Scenario: Parse variables in steps   # src/behaving/tests/features/personas.feature:10
    Given "Foo" as the persona         # src/behaving/personas/steps.py:7 2.078s
    When I set "foo" to "Hello world"  # src/behaving/personas/persona.py:40 0.000s
    And I set "bar" to "Hello world"   # src/behaving/personas/persona.py:40 0.000s
    Then "foo" is set to "$bar"        # src/behaving/personas/persona.py:40 0.000s
    When I set "foo" to "world"        # src/behaving/personas/persona.py:40 0.000s
    And I set "bar" to "Hello $foo"    # src/behaving/personas/persona.py:40 0.000s
    Then "bar" is set to "Hello world" # src/behaving/personas/persona.py:40 0.000s
    When I set "mydict.foo" to "aaa"   # src/behaving/personas/persona.py:40 0.000s

  @personas
  Scenario: Set variables text         # src/behaving/tests/features/personas.feature:21
    Given "Foo" as the persona         # src/behaving/personas/steps.py:7 2.085s
    When I set "foo" to                # src/behaving/personas/persona.py:40 0.000s
      """
      Hello world
      """
    And I set "bar" to "Hello world"   # src/behaving/personas/persona.py:40 0.000s
    Then "foo" is set to "$bar"        # src/behaving/personas/persona.py:40 0.000s
    When I set "foo" to "world"        # src/behaving/personas/persona.py:40 0.000s
    And I set "bar" to                 # src/behaving/personas/persona.py:40 0.000s
      """
      Hello $foo
      """
    Then "bar" is set to "Hello world" # src/behaving/personas/persona.py:40 0.000s

  @personas
  Scenario: Escaped persona variables     # src/behaving/tests/features/personas.feature:37
    Given "Foo" as the persona            # src/behaving/personas/steps.py:7 2.091s
    When I set "foo" to "\$1.00"          # src/behaving/personas/persona.py:40 0.000s
    And I set "bar" to "$foo Dollars"     # src/behaving/personas/persona.py:40 0.000s
    Then "bar" is set to "\$1.00 Dollars" # src/behaving/personas/persona.py:40 0.000s
    And "bar" is set to "$foo Dollars"    # src/behaving/personas/persona.py:40 0.000s
    When I set "bar" to "\$1.00 Dollars"  # src/behaving/personas/persona.py:40 0.000s
    Then "bar" is set to "\$1.00 Dollars" # src/behaving/personas/persona.py:40 0.000s
    And "bar" is set to "$foo Dollars"    # src/behaving/personas/persona.py:40 0.000s

  @personas
  Scenario: Don't start up multiple browsers  # src/behaving/tests/features/personas.feature:49
    Given I enable single browser mode        # src/behaving/web/steps/testing.py:4 0.000s
    And browser "foobar"                      # src/behaving/web/steps/browser.py:14 2.079s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    When I visit "http://localhost:8080"      # src/behaving/personas/persona.py:40 0.095s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    Given "Foo" as the persona                # src/behaving/personas/steps.py:7 0.000s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    When I visit "http://localhost:8080"      # src/behaving/personas/persona.py:40 0.043s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    And I set "bar" to "Hello world"          # src/behaving/personas/persona.py:40 0.000s
    Then "bar" is set to "Hello world"        # src/behaving/personas/persona.py:40 0.000s
    Given "Bar" as the persona                # src/behaving/personas/steps.py:7 0.000s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    When I visit "http://localhost:8080"      # src/behaving/personas/persona.py:40 0.037s
    And I set "foo" to "Hello world"          # src/behaving/personas/persona.py:40 0.000s
    And I note browser session                # src/behaving/web/steps/testing.py:9 0.000s
    Then "foo" is set to "Hello world"        # src/behaving/personas/persona.py:40 0.000s
    And I only used one browser session       # src/behaving/web/steps/testing.py:19 0.000s

  @personas
  Scenario: Clone persona                    # src/behaving/tests/features/personas.feature:70
    Given "Foo" as the persona               # src/behaving/personas/steps.py:7 2.087s
    When I set "bar" to "Hello world"        # src/behaving/personas/persona.py:40 0.000s
    When I clone persona "Foo" to "FooClone" # src/behaving/personas/steps.py:51 0.000s
    Given "FooClone" as the persona          # src/behaving/personas/steps.py:7 2.086s
    Then "bar" is set to "Hello world"       # src/behaving/personas/persona.py:40 0.000s
===== snip =====  snip ===== snip =====
1 feature passed, 0 failed, 11 skipped
6 scenarios passed, 0 failed, 40 skipped
49 steps passed, 0 failed, 264 skipped, 0 undefined
Took 0m14.793s

**Comment by ggozad** [comment]
There are indeed some regressions when using non-ascii characters on persona variables. Could you please fix and let me know when all tests pass?

**Comment by MihaiBalint** [comment]
Failing tests now pass:
$ ./bin/test --tags email
===== snip =====
1 feature passed, 0 failed, 11 skipped
6 scenarios passed, 0 failed, 40 skipped
29 steps passed, 0 failed, 284 skipped, 0 undefined
Took 0m20.642s

$ ./bin/test --tags personas
===== snip =====
2 features passed, 0 failed, 10 skipped
7 scenarios passed, 0 failed, 39 skipped
56 steps passed, 0 failed, 257 skipped, 0 undefined
Took 0m39.178s

I did not run the whole suite due to the fact that the @browser features will fail for me as I don't have appium, cordova & co installed

**Comment by ggozad** [comment]
This is fine, thanks will merge asap. We do not have appium anymore in behaving and cordova tests have no regression on this.

**Pull request merged**
