### PR TITLE
Fixed persona.py compatibility with Python 3

### PR DESCRIPTION
**Pull request by anti1869**
unicode and basestring must be replaced with str in Python 3

### CODE REVIEW

**Comment by ggozad** [comment]
Sorry for being so unresponsive on this, do all tests pass on python3?

**Comment by anti1869** [comment]
Hi, can you give me a hint how do you usually run them? Thanks

**Comment by anti1869** [comment]
Apparently, they are. Those two failures are because of me don't having those browsers on my system.

```

Failing scenarios:
  src/behaving/tests/features/browser.feature:4  Select Chrome browser
  src/behaving/tests/features/browser.feature:19  Select the cordova Chrome browser

9 features passed, 1 failed, 0 skipped
39 scenarios passed, 2 failed, 0 skipped
268 steps passed, 2 failed, 0 skipped, 0 undefined
Took 2m4.102s
```

**Comment by anti1869** [comment]
Also, ``buildout`` will not install ``supervisor``, as it is requiring Python 2.
Because of that some manual workarounds is needed to run tests.

**Comment by ggozad** [comment]
Awesome, I will merge asap. If you can be so kind and keep an eye in the future for the python 3 compat, I will be eternally grateful. Would you also add your name in the changelog and I can make a release?

**Comment by anti1869** [comment]
Thanks. I'll surely keep an eye on it, as I need ``behaving`` for my work and personal projects. We've moved forward to Python 3 and its support is crucial for us.

**Pull request merged**
